# Generated by Django 4.1.7 on 2023-07-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pri_school', models.TextField(max_length=45)),
                ('middle', models.TextField(max_length=45)),
                ('senior', models.TextField(max_length=45)),
                ('college', models.TextField(max_length=45)),
            ],
        ),
    ]
