# Generated by Django 4.1.7 on 2023-07-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='std',
            field=models.CharField(default=2, max_length=222),
            preserve_default=False,
        ),
    ]
