# Generated by Django 4.1.7 on 2023-07-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_student_std'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='area',
            field=models.CharField(max_length=223, null=True),
        ),
    ]
