# Generated by Django 4.1.7 on 2023-07-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=222)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('description', models.TextField()),
            ],
        ),
    ]
